import { defineConfig } from 'vitest/config';

import baseConfig from './vitest.config';

/**
 * Executable Creative Studio production files changed since the frozen Task 1B baseline
 * (b37e00e4f6c2ca88b1f0b5a47cbb568ff4df92af). Keep this list explicit: delivery gates review the
 * diff and extend the manifest whenever a later task changes another runtime file.
 */
const creativeStudioRuntimeManifest = [
  'packages/desktop/src/common/adapter/ipcBridge.ts',
  'packages/desktop/src/common/adapter/native/constants.ts',
  'packages/desktop/src/common/adapter/native/payloadSchemas.ts',
  'packages/desktop/src/common/types/project/creativeStudioCanonicalTake.ts',
  'packages/desktop/src/common/types/project/creativeStudioConnectionPlan.ts',
  'packages/desktop/src/common/types/project/creativeStudioDefaultRoutes.ts',
  'packages/desktop/src/common/types/project/creativeStudioManagedAssetCollections.ts',
  'packages/desktop/src/common/types/project/creativeStudioProjectSummary.ts',
  'packages/desktop/src/common/types/project/creativeStudioTypes.ts',
  'packages/desktop/src/process/bridge/creativeStudioBridge.ts',
  'packages/desktop/src/process/resources/builtinMcp/studioDirectorCommandWriter.ts',
  'packages/desktop/src/process/resources/builtinMcp/studioPendingRecordWriter.ts',
  'packages/desktop/src/process/resources/builtinMcp/studioProposalWriter.ts',
  'packages/desktop/src/process/resources/builtinMcp/studioReferenceRequestWriter.ts',
  'packages/desktop/src/process/resources/builtinMcp/studioServer.ts',
  'packages/desktop/src/process/services/creative-studio/adapters/conditioningFrame.ts',
  'packages/desktop/src/process/services/creative-studio/adapters/e2eFakeAdapter.ts',
  'packages/desktop/src/process/services/creative-studio/adapters/openRouterVideoAdapter.ts',
  'packages/desktop/src/process/services/creative-studio/childProcessTree.ts',
  'packages/desktop/src/process/services/creative-studio/ffmpegBinaries.ts',
  'packages/desktop/src/process/services/creative-studio/jobManager.ts',
  'packages/desktop/src/process/services/creative-studio/mediaStore.ts',
  'packages/desktop/src/process/services/creative-studio/providerResolver.ts',
  'packages/desktop/src/process/services/creative-studio/rateCardConfig.ts',
  'packages/desktop/src/process/services/creative-studio/runtime.ts',
  'packages/desktop/src/process/services/creative-studio/service/briefFile.ts',
  'packages/desktop/src/process/services/creative-studio/service/directorCommandContracts.ts',
  'packages/desktop/src/process/services/creative-studio/service/directorCommandMailbox.ts',
  'packages/desktop/src/process/services/creative-studio/service/directorCommandProcessor.ts',
  'packages/desktop/src/process/services/creative-studio/service/directorCommandService.ts',
  'packages/desktop/src/process/services/creative-studio/service/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/projectMutations.ts',
  'packages/desktop/src/process/services/creative-studio/service/recordIo.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/exports/catalog.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/exports/editorFolder.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/exports/pieceManifestV3.ts',
  'packages/desktop/src/process/services/creative-studio/service/filmExporter.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/exports/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/factories.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/fixedShots.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/boardPanel.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/boardRequest.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/composition.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/frameExtraction.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/generationRequest.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/referenceBinding.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/referenceRequest.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/spendMath.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/submissionIdentity.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/lifecycle.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/mutations/deletionClaimsV3.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/mutations/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/mutations/pieceCatalogV3.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/mutations/pieceHandles.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/mutations/proposalReview.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/pricing/preparedSubmissionCache.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/pricing/authorization.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/pricing/estimate.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/pricing/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/pricing/rateCard.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/projections/chain.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/projections/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/projections/projectStatus.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/projections/workspaceStatus.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/validation.ts',
  'packages/desktop/src/process/services/creative-studio/service/v2Service.ts',
  'packages/desktop/src/process/services/creative-studio/store/contracts.ts',
  'packages/desktop/src/process/services/creative-studio/store/deletionAuthority.ts',
  'packages/desktop/src/process/services/creative-studio/store/index.ts',
  'packages/desktop/src/process/services/creative-studio/store/projectRecords.ts',
  'packages/desktop/src/process/services/creative-studio/store/projectTransactions.ts',
  'packages/desktop/src/renderer/components/settings/SettingsModal/contents/ModelModalContent/StudioMediaModelsSection.tsx',
  'packages/desktop/src/renderer/pages/conversation/Messages/components/MessageToolGroupSummary.tsx',
  'packages/desktop/src/renderer/pages/conversation/Messages/components/toolActivity/buildTurnClose.ts',
  'packages/desktop/src/renderer/pages/conversation/platforms/aionrs/AionrsChat.tsx',
  'packages/desktop/src/renderer/pages/conversation/platforms/aionrs/AionrsSendBox.tsx',
  'packages/desktop/src/renderer/pages/studio/StudioPage.tsx',
  'packages/desktop/src/renderer/pages/studio/components/PlaybackAudio/index.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Library/Composer.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Library/ProjectCard.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Library/StudioLibrary.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Library/index.ts',
  'packages/desktop/src/renderer/pages/studio/components/Shell/DirectorProposalCard/index.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Shell/DirectorProposals.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/BeatPanel/BeatPlayer.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/BeatPanel/CoverageBar.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/BeatPanel/FirstFrames/index.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/BeatPanel/beatPlaybackSequence.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/BeatPanel/coverageGeometry.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/BeatPanel/segmentState.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/BeatPanel/index.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/DirectorRail/index.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/DirectorRail/openingTurn.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/DirectorRail/turnRecap.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Gate/index.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/Board/Bin.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/Board/boardShotTiles.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/Board/index.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/Cut/CutPlayer.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/Cut/filmstrip.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/Cut/filmSummary.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/Cut/index.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/Cut/playbackSequence.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/References/index.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/References/referenceRemovalBlockers.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/References/referenceStatus.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/Table/index.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/WorkspaceControls.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/WorkspaceProjectMenu.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/index.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/viewTypes.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/WorkspaceShell.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/index.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Gate/generationBlockers.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/spendGate.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/beatDisplayState.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/Views/shotStatus.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/useWorkspaceDrafts.ts',
  'packages/desktop/src/renderer/pages/studio/components/Workspace/workspaceProjection.ts',
  'packages/desktop/src/renderer/pages/studio/components/index.ts',
  'packages/desktop/src/renderer/pages/studio/hooks/index.ts',
  'packages/desktop/src/renderer/pages/studio/hooks/useStudioPlaybackAudio.tsx',
  'packages/desktop/src/renderer/pages/studio/hooks/useStudioShotAudioAnalysis.tsx',
  'packages/desktop/src/renderer/pages/studio/hooks/useStudioProject.ts',
  'packages/desktop/src/renderer/pages/studio/studioManagedAssetUrl.ts',
  'packages/desktop/src/renderer/pages/studio/studioPhaseRoute.ts',
] as const;

export default defineConfig({
  ...baseConfig,
  test: {
    ...baseConfig.test,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary', 'html'],
      reportsDirectory: './coverage/creative-studio',
      include: [...creativeStudioRuntimeManifest],
      // The root config excludes common/types as type-only. This reviewed manifest deliberately
      // includes the executable Studio helpers in that directory, so it must own an empty exclude.
      exclude: [],
      thresholds: {
        perFile: true,
        lines: 80,
        branches: 80,
      },
    },
  },
});
