import { defineConfig } from 'vitest/config';

import baseConfig from './vitest.config';

/**
 * Executable Creative Studio production files changed since the frozen Task 1B baseline
 * (b37e00e4f6c2ca88b1f0b5a47cbb568ff4df92af). Keep this list explicit: delivery gates review the
 * diff and extend the manifest whenever a later task changes another runtime file. Phase 5's clean
 * cutover intentionally omits the retained-but-unreachable schema-5 renderer modules; they are no
 * longer part of the production Studio graph and remain only as deletion follow-up evidence.
 */
const creativeStudioRuntimeManifest = [
  'packages/desktop/src/common/adapter/ipcBridge.ts',
  'packages/desktop/src/common/adapter/native/constants.ts',
  'packages/desktop/src/common/adapter/native/payloadSchemas.ts',
  'packages/desktop/src/common/types/project/creativeStudioCanonicalTake.ts',
  'packages/desktop/src/common/types/project/creativeStudioConnectionPlan.ts',
  'packages/desktop/src/common/types/project/creativeStudioDefaultRoutes.ts',
  'packages/desktop/src/common/types/project/creativeStudioManagedAssetCollections.ts',
  'packages/desktop/src/common/types/project/creativeStudioPilotMcpEnv.ts',
  'packages/desktop/src/common/types/project/creativeStudioProjectSummary.ts',
  'packages/desktop/src/common/types/project/creativeStudioTypes.ts',
  'packages/desktop/src/process/backend/sessionMcpTrust.ts',
  'packages/desktop/src/process/bridge/creativeStudioBridge.ts',
  'packages/desktop/src/process/bridge/creativeStudioCloseHandshake.ts',
  'packages/desktop/src/process/bridge/creativeStudioConnectionBridge.ts',
  'packages/desktop/src/process/bridge/creativeStudioPilotBridge.ts',
  'packages/desktop/src/process/resources/builtinMcp/studioDirectorCommandWriter.ts',
  'packages/desktop/src/process/resources/builtinMcp/pilotStudioServer.ts',
  'packages/desktop/src/process/resources/builtinMcp/studioPendingRecordWriter.ts',
  'packages/desktop/src/process/resources/builtinMcp/studioProposalWriter.ts',
  'packages/desktop/src/process/resources/builtinMcp/studioReferenceRequestWriter.ts',
  'packages/desktop/src/process/resources/builtinMcp/studioServer.ts',
  'packages/desktop/src/process/services/creative-studio/adapters/conditioningFrame.ts',
  'packages/desktop/src/process/services/creative-studio/adapters/e2eFakeAdapter.ts',
  'packages/desktop/src/process/services/creative-studio/adapters/openRouterVideoAdapter.ts',
  'packages/desktop/src/process/services/creative-studio/childProcessTree.ts',
  'packages/desktop/src/process/services/creative-studio/connectionController.ts',
  'packages/desktop/src/process/services/creative-studio/ffmpegBinaries.ts',
  'packages/desktop/src/process/services/creative-studio/jobManager.ts',
  'packages/desktop/src/process/services/creative-studio/mediaStore.ts',
  'packages/desktop/src/process/services/creative-studio/providerResolver.ts',
  'packages/desktop/src/process/services/creative-studio/pilotProductionRuntime.ts',
  'packages/desktop/src/process/services/creative-studio/rateCardConfig.ts',
  'packages/desktop/src/process/services/creative-studio/runtime.ts',
  'packages/desktop/src/process/services/creative-studio/service/briefFile.ts',
  'packages/desktop/src/process/services/creative-studio/service/durableDirectory.ts',
  'packages/desktop/src/process/services/creative-studio/service/director/contracts.ts',
  'packages/desktop/src/process/services/creative-studio/service/director/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/director/mailbox.ts',
  'packages/desktop/src/process/services/creative-studio/service/director/processor.ts',
  'packages/desktop/src/process/services/creative-studio/service/director/service.ts',
  'packages/desktop/src/process/services/creative-studio/service/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/projectMutations.ts',
  'packages/desktop/src/process/services/creative-studio/service/recordIo.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/exports/catalog.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/exports/editorFolder.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/exports/pieceManifestV3.ts',
  'packages/desktop/src/process/services/creative-studio/service/filmExporter.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/exports/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/factories.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/mutations/fixedShots.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/boardPanel.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/boardRequest.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/composition.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/frameExtraction.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/generationRequest.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/referenceBinding.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/referenceRequest.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/spendMath.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/generation/submissionIdentity.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/lifecycle.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/mutations/deletionClaimsV3.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/mutations/boardV4.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/mutations/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/mutations/pieceCatalogV3.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/mutations/pieceHandles.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/mutations/presentationV4.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/mutations/exactInputV4.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/mutations/reorderV4.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/mutations/stalenessV4.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/mutations/proposalReview.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/pricing/preparedSubmissionCache.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/pricing/authorization.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/pricing/estimate.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/pricing/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/pricing/rateCard.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/confirmation.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/contracts.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/director/contracts.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/director/mailbox.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/director/processor.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/entryPoint.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/errors.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/prepare.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/pricing.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/projections.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/runtime/factory.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/runtime/export.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/runtime/generatedUrlResolver.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/runtime/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/runtime/jobs.ts',
  'packages/desktop/src/process/services/creative-studio/service/pilot/runtime/media.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/projections/chain.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/projections/canvasV4.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/projections/index.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/projections/projectStatus.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/projections/workspaceStatus.ts',
  'packages/desktop/src/process/services/creative-studio/service/schema2/validation.ts',
  'packages/desktop/src/process/services/creative-studio/service/v2Service.ts',
  'packages/desktop/src/process/services/creative-studio/store/contracts.ts',
  'packages/desktop/src/process/services/creative-studio/store/connectionManifest.ts',
  'packages/desktop/src/process/services/creative-studio/store/deletionAuthority.ts',
  'packages/desktop/src/process/services/creative-studio/store/index.ts',
  'packages/desktop/src/process/services/creative-studio/store/projectRecords.ts',
  'packages/desktop/src/process/services/creative-studio/store/projectTransactions.ts',
  'packages/desktop/src/process/services/creative-studio/store/pilotStore.ts',
  'packages/desktop/src/process/services/creative-studio/store/proposalSidecars.ts',
  'packages/desktop/src/process/services/creative-studio/store/referenceSidecars.ts',
  'packages/desktop/src/process/services/creative-studio/store/sidecarJournal.ts',
  'packages/desktop/src/renderer/components/settings/SettingsModal/contents/ModelModalContent/StudioMediaModelsSection.tsx',
  'packages/desktop/src/renderer/pages/conversation/Messages/components/MessagePermission.tsx',
  'packages/desktop/src/renderer/pages/conversation/Messages/components/MessageToolGroupSummary.tsx',
  'packages/desktop/src/renderer/pages/conversation/Messages/components/permissionIntent.ts',
  'packages/desktop/src/renderer/pages/conversation/Messages/components/toolActivity/buildTurnClose.ts',
  'packages/desktop/src/renderer/pages/conversation/platforms/aionrs/AionrsChat.tsx',
  'packages/desktop/src/renderer/pages/conversation/platforms/aionrs/AionrsSendBox.tsx',
  'packages/desktop/src/renderer/pages/studio/StudioPage/index.tsx',
  'packages/desktop/src/renderer/pages/studio/StudioPage/pilotClient.ts',
  'packages/desktop/src/renderer/pages/studio/components/Pilot/PilotCanvas.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Pilot/PilotDirectorRail.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Pilot/PilotLibrary.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Pilot/PilotSpendingLimitDialog.tsx',
  'packages/desktop/src/renderer/pages/studio/components/Pilot/index.ts',
  'packages/desktop/src/renderer/pages/studio/studioManagedAssetUrl.ts',
] as const;

export default defineConfig({
  ...baseConfig,
  test: {
    ...baseConfig.test,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary', 'html'],
      reportsDirectory: './coverage/creative-studio',
      include: [...creativeStudioRuntimeManifest],
      // The root config excludes common/types as type-only. This reviewed manifest deliberately
      // includes the executable Studio helpers in that directory, so it must own an empty exclude.
      exclude: [],
      thresholds: {
        perFile: true,
        lines: 80,
        branches: 80,
      },
    },
  },
});
