import {
  STUDIO_MAX_PROJECT_REFERENCES,
  STUDIO_VIEWS,
  type StudioView,
} from '@/common/types/project/creativeStudioTypes';

/**
 * Re-exported, not redeclared: the view vocabulary is shared with the main process, which gates its
 * unsaved-draft close preflight on the same segments. Renderer call sites keep importing it from
 * here so the route module stays the single place the renderer reasons about view addresses.
 */
export { STUDIO_VIEWS, type StudioView };

/**
 * Deliberately not the old `last-phase:` key. The stored vocabulary changed wholesale, and
 * `parseStudioView` rejecting an unknown value already self-heals into one replace-navigation, so
 * a migration map would buy a nicer first landing at the cost of code that outlives its reason.
 */
const viewStorageKey = (projectId: string): string => `aionui:creative-studio:last-view:${projectId}`;
const SAFE_STUDIO_ID = /^[A-Za-z0-9_-]{1,256}$/;

const resolveStorage = (storage?: Storage): Storage | null => {
  if (storage !== undefined) return storage;
  try {
    return typeof window === 'undefined' ? null : window.localStorage;
  } catch {
    return null;
  }
};

export function parseStudioView(value: string | undefined): StudioView | null {
  return STUDIO_VIEWS.find((view) => view === value) ?? null;
}

export function studioViewPath(projectId: string, view: StudioView): string {
  return `/studio/${encodeURIComponent(projectId)}/${view}`;
}

/** A view-less entry lets the loaded project decide whether first-time reference work comes first. */
export function studioProjectPath(projectId: string): string {
  return `/studio/${encodeURIComponent(projectId)}`;
}

/** A new reference plan precedes the script; a project without one still begins at the Table. */
export function defaultStudioView(hasReferenceWork = false): StudioView {
  return hasReferenceWork ? 'references' : 'table';
}

export function readLastStudioView(projectId: string, storage?: Storage): StudioView | null {
  try {
    return parseStudioView(resolveStorage(storage)?.getItem(viewStorageKey(projectId)) ?? undefined);
  } catch {
    return null;
  }
}

export function rememberStudioView(projectId: string, view: StudioView, storage?: Storage): void {
  try {
    resolveStorage(storage)?.setItem(viewStorageKey(projectId), view);
  } catch {
    // View persistence is a best-effort renderer-local enhancement.
  }
}

export function resolveStudioEntryView(projectId: string, storage?: Storage, hasReferenceWork = false): StudioView {
  return readLastStudioView(projectId, storage) ?? defaultStudioView(hasReferenceWork);
}

/** A remembered choice is explicit; otherwise defer first-entry routing until the project is loaded. */
export function studioEntryPath(projectId: string, storage?: Storage): string {
  const remembered = readLastStudioView(projectId, storage);
  return remembered === null ? studioProjectPath(projectId) : studioViewPath(projectId, remembered);
}

export type StudioReferenceFocus = { referenceIds: string[]; assetIds: string[] };

const exactFocusIds = (values: readonly string[]): string[] => {
  const unique = new Set<string>();
  for (const value of values) {
    if (unique.size >= STUDIO_MAX_PROJECT_REFERENCES || !SAFE_STUDIO_ID.test(value)) continue;
    unique.add(value);
  }
  return [...unique];
};

/** A durable handoff link: query identities survive reload without putting generated bytes in history. */
export function studioReferenceReviewPath(
  projectId: string,
  focus: { referenceIds?: readonly string[]; assetIds?: readonly string[] }
): string {
  const query = new URLSearchParams();
  exactFocusIds(focus.referenceIds ?? []).forEach((id) => query.append('reference', id));
  exactFocusIds(focus.assetIds ?? []).forEach((id) => query.append('asset', id));
  const suffix = query.toString();
  return `${studioViewPath(projectId, 'references')}${suffix.length === 0 ? '' : `?${suffix}`}`;
}

export function parseStudioReferenceFocus(search: string): StudioReferenceFocus {
  const query = new URLSearchParams(search.startsWith('?') ? search.slice(1) : search);
  return {
    referenceIds: exactFocusIds(query.getAll('reference')),
    assetIds: exactFocusIds(query.getAll('asset')),
  };
}
