export { SpendGateModal, useSpendGate } from './Gate';
export type { SpendGateModalProps, UseSpendGateInput, UseSpendGateResult } from './Gate';
export { BeatPanel } from './BeatPanel';
export type { WorkspaceShotSegmentState } from './BeatPanel/segmentState';
export type {
  BeatPanelActions,
  BeatPanelImportResult,
  BeatPanelProps,
  BeatPanelReviewChoice,
  BeatPanelReviewChoiceIdentity,
  BeatPanelReviewGraph,
  BeatPanelReviewPreference,
  BeatPanelShotSave,
  StudioShotEditFocusIntent,
} from './BeatPanel';
export {
  boardGateDraft,
  boardPromotionGatePlan,
  boardSelectionGateDraft,
  continuityGateDraft,
  formatMinorUnits,
  handoffGateDraft,
  initialSpendGateState,
  majorUnitsToMinorUnits,
  selectedSpendGateQuote,
  filmRenderBatchShotIds,
  seedRegenerationGateDraft,
  selectionGateDraft,
  spendGateReducer,
  spendGateBoardPromotion,
  spendGateRouteIssue,
  spendGateContinuityChange,
  spendGateDraftIdentity,
  summarizeQuote,
} from './spendGate';
export type {
  BoardPromotionGatePlan,
  SpendGateBoardPromotion,
  SpendGateBoardPromotionImpact,
  SpendGateContinuityChange,
  SpendGateDraft,
  SpendGateGenerationDisclosure,
  SpendGatePhase,
  SpendGateQuoteSummary,
  SpendGateRouteIssue,
  SpendGateSelectedOption,
  SpendGateState,
} from './spendGate';
export {
  countStoredWorkspaceDrafts,
  hasGenerationAffectingWorkspaceDrafts,
  updateWorkspaceSelection,
  useWorkspaceDrafts,
} from './useWorkspaceDrafts';
export type {
  UseWorkspaceDraftsInput,
  UseWorkspaceDraftsResult,
  WorkspaceDraftEntry,
  WorkspaceDraftValue,
  WorkspaceSelection,
} from './useWorkspaceDrafts';
export { buildStudioBarStats, deriveStudioWorkspaceProgress, projectWorkspace } from './workspaceProjection';
export type {
  WorkspaceBinnedBeatProjection,
  WorkspaceBinnedShotProjection,
  WorkspaceBinItemProjection,
  WorkspaceBoardPanelActivity,
  WorkspaceBoardPanelFreshness,
  WorkspaceBoardPanelProjection,
  WorkspaceBoardPanelRecoveryProjection,
  WorkspaceBeatDisplayState,
  WorkspaceBeatProjection,
  WorkspaceCutAudioImportProjection,
  WorkspaceCutBeatDurationKind,
  WorkspaceCutBeatProjection,
  WorkspaceCutBedProjection,
  WorkspaceCutCoverCandidateProjection,
  WorkspaceCutProjection,
  WorkspaceProjection,
  WorkspaceCurrentPictureProjection,
  WorkspaceSeedStillProjection,
  WorkspaceShotProjection,
  StudioBarStats,
  StudioWorkspaceProgress,
  StudioWorkspaceViewProgress,
  StudioWorkspaceViewReadiness,
} from './workspaceProjection';
export { WorkspaceShell } from './WorkspaceShell';
export type {
  WorkspaceDirectorDraftRequest,
  WorkspaceReviewedOutput,
  WorkspaceShellHandle,
  WorkspaceShellProps,
} from './WorkspaceShell';
export {
  BoardView,
  CutView,
  ReferencesView,
  TableView,
  WorkspaceControls,
  WorkspaceProjectMenu,
  countStoredStudioRuleDrafts,
  tableBeatReorderOperation,
} from './Views';
export type {
  BoardActions,
  BoardViewProps,
  CutActions,
  CutImportResult,
  CutViewProps,
  ReferenceDownloadRecoveryClaim,
  ReferenceRemovalBlocker,
  ReferenceRetainedShotBinOwner,
  ReferenceRetainedShotReviewClaim,
  ReferenceWorkspaceItem,
  ReferencesViewActions,
  ReferencesViewProps,
  StudioReferenceFocusIntent,
  ReferenceBindingWorkspaceItem,
  TableAuthoringActions,
  TableReferenceBindingActions,
  TableViewProps,
  WorkspaceControlsProps,
  WorkspaceMutationCallbacks,
  WorkspaceProjectMenuProps,
} from './Views';
